export let Const = {
  circles: [
    { districtName: 'circle_01', color: 'skyblue' },
    { districtName: 'circle_02', color: 'skyblue' },
    { districtName: 'circle_03', color: 'skyblue' },
    { districtName: 'circle_04', color: 'skyblue' },
    { districtName: 'circle_05', color: 'skyblue' },
    { districtName: 'circle_06', color: 'skyblue' },
    { districtName: 'circle_07', color: 'skyblue' },
    { districtName: 'circle_08', color: 'skyblue' },
    { districtName: 'circle_09', color: 'skyblue' },
    { districtName: 'circle_10', color: 'skyblue' },
    { districtName: 'circle_11', color: 'skyblue' },
  ],
  arrows: [
    { name: 'arrow_01', color: 'red' },
    { name: 'arrow_02', color: 'red' },
    { name: 'arrow_03', color: 'red' },
    { name: 'arrow_04', color: 'red' },
    { name: 'arrow_05', color: 'red' },
    { name: 'arrow_06', color: 'red' },
    { name: 'arrow_07', color: 'red' },
    { name: 'arrow_08', color: 'red' },
    { name: 'arrow_09', color: 'red' },
    { name: 'arrow_10', color: 'red' },
  ],
}
